PROVIDER_MICROSOFT_365 = "Microsoft 365"
PROVIDER_GOOGLE_WORKSPACE = "Google Workspace"
PROVIDER_RED_SIFT = "Red Sift"
PROVIDER_VALIMAIL_ENFORCE = "Valimail Enforce"
PROVIDER_PROOFPOINT_EFD = "Proofpoint EFD"
PROVIDER_DMARC_REPORT = "DMARC Report"
PROVIDER_DMARC_ADVISOR = "DMARC Advisor"

DOMAIN_ONDMARC_COM = "ondmarc.com"
DOMAIN_DMARCIAN_COM = "dmarcian.com"
DOMAIN_SENDMARC_COM = "sendmarc.com"
DOMAIN_REDSIFT_CLOUD = "redsift.cloud"

CATEGORY_LANDING_PAGES = "Landing Pages"
CATEGORY_LIVE_CHAT = "Live Chat"

CAPABILITY_DMARC_REPORTING = "DMARC reporting"
CAPABILITY_DMARC_ENFORCEMENT = "DMARC enforcement"
CAPABILITY_DMARC_ANALYTICS = "DMARC analytics"
CAPABILITY_MTA_STS_HOSTING = "MTA-STS hosting"
CAPABILITY_SPF_MANAGEMENT = "SPF management"
CAPABILITY_TLS_RPT_REPORTING = "TLS-RPT reporting"

CNAME_PROVIDER_MAP = {
    'shopify.com': {'name': 'Shopify', 'category': 'E-commerce'},
    'myshopify.com': {'name': 'Shopify', 'category': 'E-commerce'},
    'bigcommerce.com': {'name': 'BigCommerce', 'category': 'E-commerce'},
    'squarespace.com': {'name': 'Squarespace', 'category': 'Website'},
    'wixdns.net': {'name': 'Wix', 'category': 'Website'},
    'wix.com': {'name': 'Wix', 'category': 'Website'},
    'wordpress.com': {'name': 'WordPress.com', 'category': 'Website'},
    'wpengine.com': {'name': 'WP Engine', 'category': 'Website'},
    'pantheonsite.io': {'name': 'Pantheon', 'category': 'Website'},
    'netlify.app': {'name': 'Netlify', 'category': 'Website'},
    'netlify.com': {'name': 'Netlify', 'category': 'Website'},
    'vercel.app': {'name': 'Vercel', 'category': 'Website'},
    'vercel-dns.com': {'name': 'Vercel', 'category': 'Website'},
    'webflow.io': {'name': 'Webflow', 'category': 'Website'},
    'ghost.io': {'name': 'Ghost', 'category': 'Website'},
    'cargo.site': {'name': 'Cargo', 'category': 'Website'},
    'strikingly.com': {'name': 'Strikingly', 'category': 'Website'},
    'hubspot.net': {'name': 'HubSpot', 'category': 'Marketing'},
    'hubspot.com': {'name': 'HubSpot', 'category': 'Marketing'},
    'hs-sites.com': {'name': 'HubSpot', 'category': 'Marketing'},
    'marketo.com': {'name': 'Marketo (Adobe)', 'category': 'Marketing'},
    'mktoweb.com': {'name': 'Marketo (Adobe)', 'category': 'Marketing'},
    'pardot.com': {'name': 'Pardot (Salesforce)', 'category': 'Marketing'},
    'mailchimp.com': {'name': 'Mailchimp', 'category': 'Marketing'},
    'mailgun.org': {'name': 'Mailgun', 'category': 'Email'},
    'sendgrid.net': {'name': 'SendGrid (Twilio)', 'category': 'Email'},
    'postmarkapp.com': {'name': 'Postmark', 'category': 'Email'},
    'mandrillapp.com': {'name': 'Mandrill (Mailchimp)', 'category': 'Email'},
    'zendesk.com': {'name': 'Zendesk', 'category': 'Support'},
    'zendeskhost.com': {'name': 'Zendesk', 'category': 'Support'},
    'freshdesk.com': {'name': 'Freshdesk', 'category': 'Support'},
    'freshservice.com': {'name': 'Freshservice', 'category': 'Support'},
    'intercom.io': {'name': 'Intercom', 'category': 'Support'},
    'helpscout.com': {'name': 'Help Scout', 'category': 'Support'},
    'helpscout.net': {'name': 'Help Scout', 'category': 'Support'},
    'salesforce.com': {'name': 'Salesforce', 'category': 'CRM'},
    'force.com': {'name': 'Salesforce', 'category': 'CRM'},
    'salesforceliveagent.com': {'name': 'Salesforce', 'category': 'CRM'},
    'zoho.com': {'name': 'Zoho', 'category': 'CRM'},
    'zoho.eu': {'name': 'Zoho', 'category': 'CRM'},
    'pipedrive.com': {'name': 'Pipedrive', 'category': 'CRM'},
    'cloudfront.net': {'name': 'AWS CloudFront', 'category': 'CDN'},
    'amazonaws.com': {'name': 'AWS', 'category': 'Cloud'},
    'awsglobalaccelerator.com': {'name': 'AWS Global Accelerator', 'category': 'Cloud'},
    'elasticbeanstalk.com': {'name': 'AWS Elastic Beanstalk', 'category': 'Cloud'},
    's3.amazonaws.com': {'name': 'AWS S3', 'category': 'Cloud'},
    'azurewebsites.net': {'name': 'Azure App Service', 'category': 'Cloud'},
    'azure-api.net': {'name': 'Azure API Management', 'category': 'Cloud'},
    'azurefd.net': {'name': 'Azure Front Door', 'category': 'CDN'},
    'azureedge.net': {'name': 'Azure CDN', 'category': 'CDN'},
    'trafficmanager.net': {'name': 'Azure Traffic Manager', 'category': 'Cloud'},
    'cloudapp.azure.com': {'name': 'Azure', 'category': 'Cloud'},
    'blob.core.windows.net': {'name': 'Azure Blob Storage', 'category': 'Cloud'},
    'windows.net': {'name': 'Azure', 'category': 'Cloud'},
    'googleapis.com': {'name': 'Google Cloud', 'category': 'Cloud'},
    'appspot.com': {'name': 'Google App Engine', 'category': 'Cloud'},
    'googleplex.com': {'name': 'Google', 'category': 'Cloud'},
    'run.app': {'name': 'Google Cloud Run', 'category': 'Cloud'},
    'web.app': {'name': 'Firebase Hosting', 'category': 'Cloud'},
    'firebaseapp.com': {'name': 'Firebase', 'category': 'Cloud'},
    'cdn.cloudflare.net': {'name': 'Cloudflare', 'category': 'CDN'},
    'cloudflare.net': {'name': 'Cloudflare', 'category': 'CDN'},
    'cdn77.org': {'name': 'CDN77', 'category': 'CDN'},
    'fastly.net': {'name': 'Fastly', 'category': 'CDN'},
    'edgekey.net': {'name': 'Akamai', 'category': 'CDN'},
    'akamaiedge.net': {'name': 'Akamai', 'category': 'CDN'},
    'akadns.net': {'name': 'Akamai', 'category': 'CDN'},
    'akamaized.net': {'name': 'Akamai', 'category': 'CDN'},
    'edgesuite.net': {'name': 'Akamai', 'category': 'CDN'},
    'stackpathdns.com': {'name': 'StackPath', 'category': 'CDN'},
    'stackpathcdn.com': {'name': 'StackPath', 'category': 'CDN'},
    'sucuri.net': {'name': 'Sucuri', 'category': 'Security'},
    'incapdns.net': {'name': 'Imperva (Incapsula)', 'category': 'Security'},
    'impervadns.net': {'name': 'Imperva', 'category': 'Security'},
    'heroku.com': {'name': 'Heroku', 'category': 'PaaS'},
    'herokuapp.com': {'name': 'Heroku', 'category': 'PaaS'},
    'herokudns.com': {'name': 'Heroku', 'category': 'PaaS'},
    'render.com': {'name': 'Render', 'category': 'PaaS'},
    'onrender.com': {'name': 'Render', 'category': 'PaaS'},
    'fly.dev': {'name': 'Fly.io', 'category': 'PaaS'},
    'digitaloceanspaces.com': {'name': 'DigitalOcean Spaces', 'category': 'Cloud'},
    'ondigitalocean.app': {'name': 'DigitalOcean App Platform', 'category': 'Cloud'},
    'github.io': {'name': 'GitHub Pages', 'category': 'Website'},
    'githubusercontents.com': {'name': 'GitHub', 'category': 'DevOps'},
    'gitlab.io': {'name': 'GitLab Pages', 'category': 'Website'},
    'bitbucket.io': {'name': 'Bitbucket', 'category': 'DevOps'},
    'atlassian.net': {'name': 'Atlassian', 'category': 'Collaboration'},
    'statuspage.io': {'name': 'Statuspage (Atlassian)', 'category': 'Status Page'},
    'status.io': {'name': 'Status.io', 'category': 'Status Page'},
    'readthedocs.io': {'name': 'Read the Docs', 'category': 'Documentation'},
    'gitbook.io': {'name': 'GitBook', 'category': 'Documentation'},
    'readme.io': {'name': 'ReadMe', 'category': 'Documentation'},
    'outlook.com': {'name': PROVIDER_MICROSOFT_365, 'category': 'Email'},
    'protection.outlook.com': {'name': 'Microsoft 365 (Exchange Online)', 'category': 'Email'},
    'mx.microsoft': {'name': 'Microsoft 365 (DANE)', 'category': 'Email'},
    'office365.com': {'name': PROVIDER_MICROSOFT_365, 'category': 'Email'},
    'sharepoint.com': {'name': 'SharePoint Online', 'category': 'Collaboration'},
    'lync.com': {'name': 'Skype for Business', 'category': 'Collaboration'},
    'microsoftonline.com': {'name': 'Microsoft Entra ID', 'category': 'Identity'},
    'msappproxy.net': {'name': 'Azure AD App Proxy', 'category': 'Identity'},
    'aspmx.l.google.com': {'name': PROVIDER_GOOGLE_WORKSPACE, 'category': 'Email'},
    'googlemail.com': {'name': PROVIDER_GOOGLE_WORKSPACE, 'category': 'Email'},
    'ghs.googlehosted.com': {'name': 'Google Sites', 'category': 'Website'},
    'googlehosted.com': {'name': 'Google', 'category': 'Cloud'},
    'stripe.com': {'name': 'Stripe', 'category': 'Payments'},
    'chargebee.com': {'name': 'Chargebee', 'category': 'Payments'},
    'recurly.com': {'name': 'Recurly', 'category': 'Payments'},
    'braintreegateway.com': {'name': 'Braintree (PayPal)', 'category': 'Payments'},
    'squareup.com': {'name': 'Square', 'category': 'Payments'},
    'typeform.com': {'name': 'Typeform', 'category': 'Forms'},
    'wufoo.com': {'name': 'Wufoo', 'category': 'Forms'},
    'surveygizmo.com': {'name': 'Alchemer', 'category': 'Forms'},
    'unbounce.com': {'name': 'Unbounce', 'category': CATEGORY_LANDING_PAGES},
    'instapage.com': {'name': 'Instapage', 'category': CATEGORY_LANDING_PAGES},
    'leadpages.net': {'name': 'Leadpages', 'category': CATEGORY_LANDING_PAGES},
    'canva.com': {'name': 'Canva', 'category': 'Design'},
    'calendly.com': {'name': 'Calendly', 'category': 'Scheduling'},
    'acuityscheduling.com': {'name': 'Acuity Scheduling', 'category': 'Scheduling'},
    'eventbrite.com': {'name': 'Eventbrite', 'category': 'Events'},
    'zoom.us': {'name': 'Zoom', 'category': 'Video'},
    'webex.com': {'name': 'Webex (Cisco)', 'category': 'Video'},
    'auth0.com': {'name': 'Auth0 (Okta)', 'category': 'Identity'},
    'okta.com': {'name': 'Okta', 'category': 'Identity'},
    'onelogin.com': {'name': 'OneLogin', 'category': 'Identity'},
    'duosecurity.com': {'name': 'Duo (Cisco)', 'category': 'Identity'},
    'greenhouse.io': {'name': 'Greenhouse', 'category': 'Recruiting'},
    'lever.co': {'name': 'Lever', 'category': 'Recruiting'},
    'workday.com': {'name': 'Workday', 'category': 'HR'},
    'bamboohr.com': {'name': 'BambooHR', 'category': 'HR'},
    'namely.com': {'name': 'Namely', 'category': 'HR'},
    'gusto.com': {'name': 'Gusto', 'category': 'HR'},
    'slack.com': {'name': 'Slack', 'category': 'Collaboration'},
    'notion.so': {'name': 'Notion', 'category': 'Collaboration'},
    'monday.com': {'name': 'monday.com', 'category': 'Collaboration'},
    'asana.com': {'name': 'Asana', 'category': 'Collaboration'},
    'pagerduty.com': {'name': 'PagerDuty', 'category': 'Monitoring'},
    'datadoghq.com': {'name': 'Datadog', 'category': 'Monitoring'},
    'datadoghq.eu': {'name': 'Datadog', 'category': 'Monitoring'},
    'sentry.io': {'name': 'Sentry', 'category': 'Monitoring'},
    'newrelic.com': {'name': 'New Relic', 'category': 'Monitoring'},
    'sumologic.com': {'name': 'Sumo Logic', 'category': 'Monitoring'},
    'grafana.net': {'name': 'Grafana Cloud', 'category': 'Monitoring'},
    'docusign.com': {'name': 'DocuSign', 'category': 'Documents'},
    'docusign.net': {'name': 'DocuSign', 'category': 'Documents'},
    'hellosign.com': {'name': 'HelloSign (Dropbox)', 'category': 'Documents'},
    'box.com': {'name': 'Box', 'category': 'Storage'},
    'dropbox.com': {'name': 'Dropbox', 'category': 'Storage'},
    'egnyte.com': {'name': 'Egnyte', 'category': 'Storage'},
    'teachable.com': {'name': 'Teachable', 'category': 'Learning'},
    'thinkific.com': {'name': 'Thinkific', 'category': 'Learning'},
    'kajabi.com': {'name': 'Kajabi', 'category': 'Learning'},
    'discourse.org': {'name': 'Discourse', 'category': 'Community'},
    'discourse.cloud': {'name': 'Discourse', 'category': 'Community'},
    'mattermost.com': {'name': 'Mattermost', 'category': 'Collaboration'},
    'tawk.to': {'name': 'tawk.to', 'category': CATEGORY_LIVE_CHAT},
    'crisp.chat': {'name': 'Crisp', 'category': CATEGORY_LIVE_CHAT},
    'drift.com': {'name': 'Drift', 'category': CATEGORY_LIVE_CHAT},
    'livechatinc.com': {'name': 'LiveChat', 'category': CATEGORY_LIVE_CHAT},
    'segment.com': {'name': 'Segment (Twilio)', 'category': 'Analytics'},
    'segment.io': {'name': 'Segment (Twilio)', 'category': 'Analytics'},
    'amplitude.com': {'name': 'Amplitude', 'category': 'Analytics'},
    'mixpanel.com': {'name': 'Mixpanel', 'category': 'Analytics'},
    'hotjar.com': {'name': 'Hotjar', 'category': 'Analytics'},
    'optimizely.com': {'name': 'Optimizely', 'category': 'Analytics'},
    'crazyegg.com': {'name': 'Crazy Egg', 'category': 'Analytics'},
    'wpenginepowered.com': {'name': 'WP Engine', 'category': 'Website'},
    'flywheel.io': {'name': 'Flywheel', 'category': 'Website'},
    'kinsta.cloud': {'name': 'Kinsta', 'category': 'Website'},
    'cloudwaysapps.com': {'name': 'Cloudways', 'category': 'Website'},
    'siteground.net': {'name': 'SiteGround', 'category': 'Hosting'},
    'bluehost.com': {'name': 'Bluehost', 'category': 'Hosting'},
    'godaddysites.com': {'name': 'GoDaddy', 'category': 'Hosting'},
    'secureserver.net': {'name': 'GoDaddy', 'category': 'Hosting'},
    'hostgator.com': {'name': 'HostGator', 'category': 'Hosting'},
    'dreamhost.com': {'name': 'DreamHost', 'category': 'Hosting'},
    'wpcomstaging.com': {'name': 'WordPress.com', 'category': 'Website'},
    'service-now.com': {'name': 'ServiceNow', 'category': 'ITSM'},
    'servicenow.com': {'name': 'ServiceNow', 'category': 'ITSM'},
}

DMARC_MONITORING_PROVIDERS = {
    DOMAIN_ONDMARC_COM: {'name': 'OnDMARC', 'vendor': PROVIDER_RED_SIFT, 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_TLS_RPT_REPORTING, CAPABILITY_SPF_MANAGEMENT, CAPABILITY_MTA_STS_HOSTING]},
    'valimail.com': {'name': PROVIDER_VALIMAIL_ENFORCE, 'vendor': 'Valimail', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ENFORCEMENT, CAPABILITY_SPF_MANAGEMENT]},
    DOMAIN_DMARCIAN_COM: {'name': 'Dmarcian', 'vendor': 'Dmarcian', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'easydmarc.com': {'name': 'EasyDMARC', 'vendor': 'EasyDMARC', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS, CAPABILITY_SPF_MANAGEMENT]},
    'powerdmarc.com': {'name': 'PowerDMARC', 'vendor': 'PowerDMARC', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ENFORCEMENT, CAPABILITY_SPF_MANAGEMENT]},
    'agari.com': {'name': 'Agari', 'vendor': 'Fortra (HelpSystems)', 'capabilities': [CAPABILITY_DMARC_REPORTING, 'brand protection']},
    'dmarc-analyzer.com': {'name': 'DMARC Analyzer', 'vendor': 'Mimecast', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'postmarkapp.com': {'name': 'Postmark DMARC', 'vendor': 'ActiveCampaign', 'capabilities': [CAPABILITY_DMARC_REPORTING]},
    'uriports.com': {'name': 'URIports', 'vendor': 'URIports', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_TLS_RPT_REPORTING]},
    'fraudmarc.com': {'name': 'Fraudmarc', 'vendor': 'Fraudmarc', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_SPF_MANAGEMENT]},
    'mxtoolbox.com': {'name': 'MxToolbox', 'vendor': 'MxToolbox', 'capabilities': [CAPABILITY_DMARC_REPORTING]},
    DOMAIN_SENDMARC_COM: {'name': 'Sendmarc', 'vendor': 'Sendmarc', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ENFORCEMENT]},
    'proofpoint.com': {'name': PROVIDER_PROOFPOINT_EFD, 'vendor': 'Proofpoint', 'capabilities': [CAPABILITY_DMARC_REPORTING, 'email fraud defense']},
    'redsift.com': {'name': PROVIDER_RED_SIFT, 'vendor': PROVIDER_RED_SIFT, 'capabilities': [CAPABILITY_DMARC_REPORTING]},
    'mailhardener.com': {'name': 'Mailhardener', 'vendor': 'Mailhardener', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_MTA_STS_HOSTING]},
    'dmarc.postmarkapp.com': {'name': 'Postmark DMARC', 'vendor': 'ActiveCampaign', 'capabilities': [CAPABILITY_DMARC_REPORTING]},
    'emailsecuritycheck.net': {'name': PROVIDER_DMARC_REPORT, 'vendor': PROVIDER_DMARC_REPORT, 'capabilities': [CAPABILITY_DMARC_REPORTING]},
    'app.dmarcdigests.com': {'name': 'DMARC Digests', 'vendor': 'DMARC Digests', 'capabilities': [CAPABILITY_DMARC_REPORTING]},
    'dmarc.report': {'name': PROVIDER_DMARC_REPORT, 'vendor': PROVIDER_DMARC_REPORT, 'capabilities': [CAPABILITY_DMARC_REPORTING]},
    'ag.dmarcly.com': {'name': 'DMARCLY', 'vendor': 'DMARCLY', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'dmarcly.com': {'name': 'DMARCLY', 'vendor': 'DMARCLY', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'dmarc-reports.cloudflare.net': {'name': 'Cloudflare DMARC', 'vendor': 'Cloudflare', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'cloudflare.net': {'name': 'Cloudflare DMARC', 'vendor': 'Cloudflare', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'glockapps.com': {'name': 'GlockApps', 'vendor': 'GlockApps', 'capabilities': [CAPABILITY_DMARC_REPORTING, 'deliverability testing']},
    'dmarcadvisor.com': {'name': PROVIDER_DMARC_ADVISOR, 'vendor': PROVIDER_DMARC_ADVISOR, 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'dmarcmanager.app': {'name': PROVIDER_DMARC_ADVISOR, 'vendor': PROVIDER_DMARC_ADVISOR, 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_DMARC_ANALYTICS]},
    'dmarcduty.com': {'name': 'DynamicSPF', 'vendor': 'Dmarcduty', 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_SPF_MANAGEMENT]},
    'dmarcreport.com': {'name': PROVIDER_DMARC_REPORT, 'vendor': PROVIDER_DMARC_REPORT, 'capabilities': [CAPABILITY_DMARC_REPORTING, 'AI-assisted analysis']},
    'ironscales.com': {'name': 'IRONSCALES', 'vendor': 'IRONSCALES', 'capabilities': [CAPABILITY_DMARC_REPORTING, 'email security']},
    DOMAIN_REDSIFT_CLOUD: {'name': 'OnDMARC', 'vendor': PROVIDER_RED_SIFT, 'capabilities': [CAPABILITY_DMARC_REPORTING, CAPABILITY_TLS_RPT_REPORTING, CAPABILITY_SPF_MANAGEMENT, CAPABILITY_MTA_STS_HOSTING]},
}

SPF_FLATTENING_PROVIDERS = {
    DOMAIN_ONDMARC_COM: {'name': 'OnDMARC', 'vendor': PROVIDER_RED_SIFT},
    'smart.ondmarc.com': {'name': 'OnDMARC', 'vendor': PROVIDER_RED_SIFT},
    DOMAIN_REDSIFT_CLOUD: {'name': 'OnDMARC', 'vendor': PROVIDER_RED_SIFT},
    'vali.email': {'name': PROVIDER_VALIMAIL_ENFORCE, 'vendor': 'Valimail'},
    'valimail.com': {'name': PROVIDER_VALIMAIL_ENFORCE, 'vendor': 'Valimail'},
    'autospf.com': {'name': 'AutoSPF', 'vendor': 'AutoSPF'},
    DOMAIN_SENDMARC_COM: {'name': 'Sendmarc', 'vendor': 'Sendmarc'},
    'fraudmarc.com': {'name': 'Fraudmarc', 'vendor': 'Fraudmarc'},
    DOMAIN_DMARCIAN_COM: {'name': 'Dmarcian', 'vendor': 'Dmarcian'},
    'easydmarc.pro': {'name': 'EasySPF', 'vendor': 'EasyDMARC'},
    'easydmarc.com': {'name': 'EasySPF', 'vendor': 'EasyDMARC'},
    'powerspf.com': {'name': 'PowerSPF', 'vendor': 'PowerDMARC'},
    'powerdmarc.com': {'name': 'PowerSPF', 'vendor': 'PowerDMARC'},
    'dmarcly.com': {'name': 'DMARCLY', 'vendor': 'DMARCLY'},
    'dmarcduty.com': {'name': 'DynamicSPF', 'vendor': 'Dmarcduty'},
    'spf.has.gpphosted.com': {'name': 'Proofpoint EFD (Gov)', 'vendor': 'Proofpoint'},
    'spf.has.pphosted.com': {'name': PROVIDER_PROOFPOINT_EFD, 'vendor': 'Proofpoint'},
}

DYNAMIC_SERVICES_PROVIDERS = {
    DOMAIN_ONDMARC_COM: {'name': 'OnDMARC', 'vendor': PROVIDER_RED_SIFT},
    DOMAIN_REDSIFT_CLOUD: {'name': 'OnDMARC', 'vendor': PROVIDER_RED_SIFT},
    'mailhardener.com': {'name': 'Mailhardener', 'vendor': 'Mailhardener'},
    'vali.email': {'name': PROVIDER_VALIMAIL_ENFORCE, 'vendor': 'Valimail'},
}

DYNAMIC_SERVICES_ZONES = {
    '_dmarc': 'Dynamic DMARC',
    '_domainkey': 'Dynamic DKIM',
    '_mta-sts': 'Dynamic MTA-STS',
    '_smtp._tls': 'Dynamic TLS-RPT',
}

HOSTED_DKIM_PROVIDERS = {
    'gpphosted.com': {'name': 'Proofpoint EFD (Gov)', 'vendor': 'Proofpoint'},
    'pphosted.com': {'name': PROVIDER_PROOFPOINT_EFD, 'vendor': 'Proofpoint'},
    'proofpoint.com': {'name': PROVIDER_PROOFPOINT_EFD, 'vendor': 'Proofpoint'},
    'dkim.mimecast.com': {'name': 'Mimecast DMARC Analyzer', 'vendor': 'Mimecast'},
    'mimecast.com': {'name': 'Mimecast DMARC Analyzer', 'vendor': 'Mimecast'},
    'agari.com': {'name': 'Agari', 'vendor': 'Fortra'},
    'emailsecurity.fortra.com': {'name': 'Agari', 'vendor': 'Fortra'},
    DOMAIN_SENDMARC_COM: {'name': 'Sendmarc', 'vendor': 'Sendmarc'},
    DOMAIN_DMARCIAN_COM: {'name': 'Dmarcian', 'vendor': 'Dmarcian'},
}

DANE_MX_CAPABILITY = {
    'google': {
        'name': PROVIDER_GOOGLE_WORKSPACE,
        'dane_inbound': False,
        'dane_outbound': False,
        'reason': 'Google uses shared, multi-tenant MX infrastructure (aspmx.l.google.com) with certificate rotation. Google does not publish TLSA records for its MX hosts and does not allow customers to do so. Google also does not validate DANE/TLSA when sending outbound mail.',
        'alternative': 'MTA-STS',
        'patterns': ['google.com', 'googlemail.com', 'smtp.goog'],
    },
    'microsoft_dane': {
        'name': 'Microsoft 365 (DANE-enabled)',
        'dane_inbound': True,
        'dane_outbound': True,
        'reason': 'Microsoft 365 supports inbound DANE with DNSSEC (GA October 2024) via *.mx.microsoft endpoints, and validates DANE/TLSA on outbound SMTP.',
        'patterns': ['mx.microsoft'],
    },
    'microsoft_legacy': {
        'name': PROVIDER_MICROSOFT_365,
        'dane_inbound': False,
        'dane_outbound': True,
        'dane_migration_available': True,
        'reason': 'This domain uses legacy Microsoft 365 MX endpoints (*.mail.protection.outlook.com) which do not publish TLSA records. Microsoft supports DANE with DNSSEC on newer *.mx.microsoft.com endpoints (GA October 2024). Migrating MX records enables inbound DANE. Microsoft does validate DANE/TLSA when sending outbound mail.',
        'alternative': 'Migrate MX to *.mx.microsoft.com endpoints for inbound DANE, or use MTA-STS',
        'patterns': ['outlook.com', 'protection.outlook.com', 'olc.protection.outlook.com'],
    },
    'protonmail': {
        'name': 'Proton Mail',
        'dane_inbound': True,
        'dane_outbound': True,
        'reason': 'Proton Mail publishes DANE/TLSA records for its MX hosts and validates DANE on outbound delivery.',
        'patterns': ['protonmail.ch', 'mail.protonmail.ch'],
    },
    'zoho': {
        'name': 'Zoho Mail',
        'dane_inbound': False,
        'dane_outbound': False,
        'reason': 'Zoho does not publish TLSA records for its MX hosts. Zoho MX infrastructure is shared and does not support per-customer DANE.',
        'alternative': 'MTA-STS',
        'patterns': ['zoho.com', 'zoho.eu', 'zoho.in'],
    },
    'fastmail': {
        'name': 'Fastmail',
        'dane_inbound': True,
        'dane_outbound': True,
        'reason': 'Fastmail publishes DANE/TLSA records for its MX hosts and supports DNSSEC.',
        'patterns': ['fastmail.com', 'messagingengine.com'],
    },
    'mimecast': {
        'name': 'Mimecast',
        'dane_inbound': False,
        'dane_outbound': False,
        'reason': 'Mimecast is a security gateway with shared MX infrastructure. It does not publish per-customer TLSA records.',
        'alternative': 'MTA-STS',
        'patterns': ['mimecast.com'],
    },
    'proofpoint': {
        'name': 'Proofpoint',
        'dane_inbound': False,
        'dane_outbound': False,
        'reason': 'Proofpoint is a security gateway with shared MX infrastructure. It does not publish per-customer TLSA records.',
        'alternative': 'MTA-STS',
        'patterns': ['pphosted.com', 'ppe-hosted.com'],
    },
    'barracuda': {
        'name': 'Barracuda',
        'dane_inbound': False,
        'dane_outbound': False,
        'reason': 'Barracuda is a security gateway with shared MX infrastructure. It does not publish per-customer TLSA records.',
        'alternative': 'MTA-STS',
        'patterns': ['barracudanetworks.com'],
    },
    'icloud': {
        'name': 'iCloud Mail',
        'dane_inbound': False,
        'dane_outbound': False,
        'reason': 'Apple iCloud Mail does not publish TLSA records for its MX hosts.',
        'alternative': 'MTA-STS',
        'patterns': ['icloud.com'],
    },
    'yahoo': {
        'name': 'Yahoo Mail',
        'dane_inbound': False,
        'dane_outbound': False,
        'reason': 'Yahoo Mail does not publish TLSA records for its MX hosts.',
        'alternative': 'MTA-STS',
        'patterns': ['yahoodns.net'],
    },
}
