// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbq

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisStat struct {
	ID                 int32            `db:"id" json:"id"`
	Date               pgtype.Date      `db:"date" json:"date"`
	TotalAnalyses      *int32           `db:"total_analyses" json:"total_analyses"`
	SuccessfulAnalyses *int32           `db:"successful_analyses" json:"successful_analyses"`
	FailedAnalyses     *int32           `db:"failed_analyses" json:"failed_analyses"`
	UniqueDomains      *int32           `db:"unique_domains" json:"unique_domains"`
	AvgAnalysisTime    *float64         `db:"avg_analysis_time" json:"avg_analysis_time"`
	CreatedAt          pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type DomainAnalysis struct {
	ID                   int32            `db:"id" json:"id"`
	Domain               string           `db:"domain" json:"domain"`
	AsciiDomain          string           `db:"ascii_domain" json:"ascii_domain"`
	BasicRecords         json.RawMessage  `db:"basic_records" json:"basic_records"`
	AuthoritativeRecords json.RawMessage  `db:"authoritative_records" json:"authoritative_records"`
	SpfStatus            *string          `db:"spf_status" json:"spf_status"`
	SpfRecords           json.RawMessage  `db:"spf_records" json:"spf_records"`
	DmarcStatus          *string          `db:"dmarc_status" json:"dmarc_status"`
	DmarcPolicy          *string          `db:"dmarc_policy" json:"dmarc_policy"`
	DmarcRecords         json.RawMessage  `db:"dmarc_records" json:"dmarc_records"`
	DkimStatus           *string          `db:"dkim_status" json:"dkim_status"`
	DkimSelectors        json.RawMessage  `db:"dkim_selectors" json:"dkim_selectors"`
	RegistrarName        *string          `db:"registrar_name" json:"registrar_name"`
	RegistrarSource      *string          `db:"registrar_source" json:"registrar_source"`
	AnalysisSuccess      *bool            `db:"analysis_success" json:"analysis_success"`
	ErrorMessage         *string          `db:"error_message" json:"error_message"`
	AnalysisDuration     *float64         `db:"analysis_duration" json:"analysis_duration"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	CountryCode          *string          `db:"country_code" json:"country_code"`
	CountryName          *string          `db:"country_name" json:"country_name"`
	CtSubdomains         json.RawMessage  `db:"ct_subdomains" json:"ct_subdomains"`
	FullResults          json.RawMessage  `db:"full_results" json:"full_results"`
}
