package analyzer

type managementProviderInfo struct {
	Name         string
	Vendor       string
	Capabilities []string
}

type spfFlatteningInfo struct {
	Name   string
	Vendor string
}

type hostedDKIMInfo struct {
	Name   string
	Vendor string
}

type dynamicServiceInfo struct {
	Name   string
	Vendor string
}

type cnameProviderInfo struct {
	Name     string
	Category string
}

var dmarcMonitoringProviders = map[string]managementProviderInfo{
	"ondmarc.com":                   {Name: "OnDMARC", Vendor: "Red Sift", Capabilities: []string{"DMARC reporting", "TLS-RPT reporting", "SPF management", "MTA-STS hosting"}},
	"valimail.com":                  {Name: "Valimail Enforce", Vendor: "Valimail", Capabilities: []string{"DMARC reporting", "DMARC enforcement", "SPF management"}},
	"dmarcian.com":                  {Name: "Dmarcian", Vendor: "Dmarcian", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"easydmarc.com":                 {Name: "EasyDMARC", Vendor: "EasyDMARC", Capabilities: []string{"DMARC reporting", "DMARC analytics", "SPF management"}},
	"powerdmarc.com":                {Name: "PowerDMARC", Vendor: "PowerDMARC", Capabilities: []string{"DMARC reporting", "DMARC enforcement", "SPF management"}},
	"agari.com":                     {Name: "Agari", Vendor: "Fortra (HelpSystems)", Capabilities: []string{"DMARC reporting", "brand protection"}},
	"dmarc-analyzer.com":            {Name: "DMARC Analyzer", Vendor: "Mimecast", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"postmarkapp.com":               {Name: "Postmark DMARC", Vendor: "ActiveCampaign", Capabilities: []string{"DMARC reporting"}},
	"uriports.com":                  {Name: "URIports", Vendor: "URIports", Capabilities: []string{"DMARC reporting", "TLS-RPT reporting"}},
	"fraudmarc.com":                 {Name: "Fraudmarc", Vendor: "Fraudmarc", Capabilities: []string{"DMARC reporting", "SPF management"}},
	"mxtoolbox.com":                 {Name: "MxToolbox", Vendor: "MxToolbox", Capabilities: []string{"DMARC reporting"}},
	"sendmarc.com":                  {Name: "Sendmarc", Vendor: "Sendmarc", Capabilities: []string{"DMARC reporting", "DMARC enforcement"}},
	"proofpoint.com":                {Name: "Proofpoint EFD", Vendor: "Proofpoint", Capabilities: []string{"DMARC reporting", "email fraud defense"}},
	"redsift.com":                   {Name: "Red Sift", Vendor: "Red Sift", Capabilities: []string{"DMARC reporting"}},
	"mailhardener.com":              {Name: "Mailhardener", Vendor: "Mailhardener", Capabilities: []string{"DMARC reporting", "MTA-STS hosting"}},
	"dmarc.postmarkapp.com":         {Name: "Postmark DMARC", Vendor: "ActiveCampaign", Capabilities: []string{"DMARC reporting"}},
	"emailsecuritycheck.net":        {Name: "DMARC Report", Vendor: "DMARC Report", Capabilities: []string{"DMARC reporting"}},
	"app.dmarcdigests.com":          {Name: "DMARC Digests", Vendor: "DMARC Digests", Capabilities: []string{"DMARC reporting"}},
	"dmarc.report":                  {Name: "DMARC Report", Vendor: "DMARC Report", Capabilities: []string{"DMARC reporting"}},
	"ag.dmarcly.com":                {Name: "DMARCLY", Vendor: "DMARCLY", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"dmarcly.com":                   {Name: "DMARCLY", Vendor: "DMARCLY", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"dmarc-reports.cloudflare.net":  {Name: "Cloudflare DMARC", Vendor: "Cloudflare", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"cloudflare.net":                {Name: "Cloudflare DMARC", Vendor: "Cloudflare", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"glockapps.com":                 {Name: "GlockApps", Vendor: "GlockApps", Capabilities: []string{"DMARC reporting", "deliverability testing"}},
	"dmarcadvisor.com":              {Name: "DMARC Advisor", Vendor: "DMARC Advisor", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"dmarcmanager.app":              {Name: "DMARC Advisor", Vendor: "DMARC Advisor", Capabilities: []string{"DMARC reporting", "DMARC analytics"}},
	"dmarcduty.com":                 {Name: "DynamicSPF", Vendor: "Dmarcduty", Capabilities: []string{"DMARC reporting", "SPF management"}},
	"dmarcreport.com":               {Name: "DMARC Report", Vendor: "DMARC Report", Capabilities: []string{"DMARC reporting", "AI-assisted analysis"}},
	"ironscales.com":                {Name: "IRONSCALES", Vendor: "IRONSCALES", Capabilities: []string{"DMARC reporting", "email security"}},
	"redsift.cloud":                 {Name: "OnDMARC", Vendor: "Red Sift", Capabilities: []string{"DMARC reporting", "TLS-RPT reporting", "SPF management", "MTA-STS hosting"}},
}

var spfFlatteningProviders = map[string]spfFlatteningInfo{
	"ondmarc.com":       {Name: "OnDMARC", Vendor: "Red Sift"},
	"smart.ondmarc.com": {Name: "OnDMARC", Vendor: "Red Sift"},
	"redsift.cloud":     {Name: "OnDMARC", Vendor: "Red Sift"},
	"vali.email":        {Name: "Valimail Enforce", Vendor: "Valimail"},
	"valimail.com":      {Name: "Valimail Enforce", Vendor: "Valimail"},
	"autospf.com":       {Name: "AutoSPF", Vendor: "AutoSPF"},
	"sendmarc.com":      {Name: "Sendmarc", Vendor: "Sendmarc"},
	"fraudmarc.com":     {Name: "Fraudmarc", Vendor: "Fraudmarc"},
	"dmarcian.com":      {Name: "Dmarcian", Vendor: "Dmarcian"},
	"easydmarc.pro":     {Name: "EasySPF", Vendor: "EasyDMARC"},
	"easydmarc.com":     {Name: "EasySPF", Vendor: "EasyDMARC"},
	"powerspf.com":      {Name: "PowerSPF", Vendor: "PowerDMARC"},
	"powerdmarc.com":    {Name: "PowerSPF", Vendor: "PowerDMARC"},
	"dmarcly.com":       {Name: "DMARCLY", Vendor: "DMARCLY"},
	"dmarcduty.com":     {Name: "DynamicSPF", Vendor: "Dmarcduty"},
	"spf.has.gpphosted.com": {Name: "Proofpoint EFD (Gov)", Vendor: "Proofpoint"},
	"spf.has.pphosted.com":  {Name: "Proofpoint EFD", Vendor: "Proofpoint"},
}

var hostedDKIMProviders = map[string]hostedDKIMInfo{
	"gpphosted.com":             {Name: "Proofpoint EFD (Gov)", Vendor: "Proofpoint"},
	"pphosted.com":              {Name: "Proofpoint EFD", Vendor: "Proofpoint"},
	"proofpoint.com":            {Name: "Proofpoint EFD", Vendor: "Proofpoint"},
	"dkim.mimecast.com":         {Name: "Mimecast DMARC Analyzer", Vendor: "Mimecast"},
	"mimecast.com":              {Name: "Mimecast DMARC Analyzer", Vendor: "Mimecast"},
	"agari.com":                 {Name: "Agari", Vendor: "Fortra"},
	"emailsecurity.fortra.com":  {Name: "Agari", Vendor: "Fortra"},
	"sendmarc.com":              {Name: "Sendmarc", Vendor: "Sendmarc"},
	"dmarcian.com":              {Name: "Dmarcian", Vendor: "Dmarcian"},
}

var dynamicServicesProviders = map[string]dynamicServiceInfo{
	"ondmarc.com":      {Name: "OnDMARC", Vendor: "Red Sift"},
	"redsift.cloud":    {Name: "OnDMARC", Vendor: "Red Sift"},
	"mailhardener.com": {Name: "Mailhardener", Vendor: "Mailhardener"},
	"vali.email":       {Name: "Valimail Enforce", Vendor: "Valimail"},
}

var dynamicServicesZones = map[string]string{
	"_dmarc":     "Dynamic DMARC",
	"_domainkey": "Dynamic DKIM",
	"_mta-sts":   "Dynamic MTA-STS",
	"_smtp._tls": "Dynamic TLS-RPT",
}

var cnameProviderMap = map[string]cnameProviderInfo{
	"shopify.com":               {Name: "Shopify", Category: "E-commerce"},
	"myshopify.com":             {Name: "Shopify", Category: "E-commerce"},
	"bigcommerce.com":           {Name: "BigCommerce", Category: "E-commerce"},
	"squarespace.com":           {Name: "Squarespace", Category: "Website"},
	"wixdns.net":                {Name: "Wix", Category: "Website"},
	"wix.com":                   {Name: "Wix", Category: "Website"},
	"wordpress.com":             {Name: "WordPress.com", Category: "Website"},
	"wpengine.com":              {Name: "WP Engine", Category: "Website"},
	"pantheonsite.io":           {Name: "Pantheon", Category: "Website"},
	"netlify.app":               {Name: "Netlify", Category: "Website"},
	"netlify.com":               {Name: "Netlify", Category: "Website"},
	"vercel.app":                {Name: "Vercel", Category: "Website"},
	"vercel-dns.com":            {Name: "Vercel", Category: "Website"},
	"webflow.io":                {Name: "Webflow", Category: "Website"},
	"ghost.io":                  {Name: "Ghost", Category: "Website"},
	"cargo.site":                {Name: "Cargo", Category: "Website"},
	"strikingly.com":            {Name: "Strikingly", Category: "Website"},
	"hubspot.net":               {Name: "HubSpot", Category: "Marketing"},
	"hubspot.com":               {Name: "HubSpot", Category: "Marketing"},
	"hs-sites.com":              {Name: "HubSpot", Category: "Marketing"},
	"marketo.com":               {Name: "Marketo (Adobe)", Category: "Marketing"},
	"mktoweb.com":               {Name: "Marketo (Adobe)", Category: "Marketing"},
	"pardot.com":                {Name: "Pardot (Salesforce)", Category: "Marketing"},
	"mailchimp.com":             {Name: "Mailchimp", Category: "Marketing"},
	"mailgun.org":               {Name: "Mailgun", Category: "Email"},
	"sendgrid.net":              {Name: "SendGrid (Twilio)", Category: "Email"},
	"postmarkapp.com":           {Name: "Postmark", Category: "Email"},
	"mandrillapp.com":           {Name: "Mandrill (Mailchimp)", Category: "Email"},
	"zendesk.com":               {Name: "Zendesk", Category: "Support"},
	"zendeskhost.com":           {Name: "Zendesk", Category: "Support"},
	"freshdesk.com":             {Name: "Freshdesk", Category: "Support"},
	"freshservice.com":          {Name: "Freshservice", Category: "Support"},
	"intercom.io":               {Name: "Intercom", Category: "Support"},
	"helpscout.com":             {Name: "Help Scout", Category: "Support"},
	"helpscout.net":             {Name: "Help Scout", Category: "Support"},
	"salesforce.com":            {Name: "Salesforce", Category: "CRM"},
	"force.com":                 {Name: "Salesforce", Category: "CRM"},
	"salesforceliveagent.com":   {Name: "Salesforce", Category: "CRM"},
	"zoho.com":                  {Name: "Zoho", Category: "CRM"},
	"zoho.eu":                   {Name: "Zoho", Category: "CRM"},
	"pipedrive.com":             {Name: "Pipedrive", Category: "CRM"},
	"cloudfront.net":            {Name: "AWS CloudFront", Category: "CDN"},
	"amazonaws.com":             {Name: "AWS", Category: "Cloud"},
	"awsglobalaccelerator.com":  {Name: "AWS Global Accelerator", Category: "Cloud"},
	"elasticbeanstalk.com":      {Name: "AWS Elastic Beanstalk", Category: "Cloud"},
	"s3.amazonaws.com":          {Name: "AWS S3", Category: "Cloud"},
	"azurewebsites.net":         {Name: "Azure App Service", Category: "Cloud"},
	"azure-api.net":             {Name: "Azure API Management", Category: "Cloud"},
	"azurefd.net":               {Name: "Azure Front Door", Category: "CDN"},
	"azureedge.net":             {Name: "Azure CDN", Category: "CDN"},
	"trafficmanager.net":        {Name: "Azure Traffic Manager", Category: "Cloud"},
	"cloudapp.azure.com":        {Name: "Azure", Category: "Cloud"},
	"blob.core.windows.net":     {Name: "Azure Blob Storage", Category: "Cloud"},
	"windows.net":               {Name: "Azure", Category: "Cloud"},
	"googleapis.com":            {Name: "Google Cloud", Category: "Cloud"},
	"appspot.com":               {Name: "Google App Engine", Category: "Cloud"},
	"googleplex.com":            {Name: "Google", Category: "Cloud"},
	"run.app":                   {Name: "Google Cloud Run", Category: "Cloud"},
	"web.app":                   {Name: "Firebase Hosting", Category: "Cloud"},
	"firebaseapp.com":           {Name: "Firebase", Category: "Cloud"},
	"cdn.cloudflare.net":        {Name: "Cloudflare", Category: "CDN"},
	"cloudflare.net":            {Name: "Cloudflare", Category: "CDN"},
	"cdn77.org":                 {Name: "CDN77", Category: "CDN"},
	"fastly.net":                {Name: "Fastly", Category: "CDN"},
	"edgekey.net":               {Name: "Akamai", Category: "CDN"},
	"akamaiedge.net":            {Name: "Akamai", Category: "CDN"},
	"akadns.net":                {Name: "Akamai", Category: "CDN"},
	"akamaized.net":             {Name: "Akamai", Category: "CDN"},
	"edgesuite.net":             {Name: "Akamai", Category: "CDN"},
	"stackpathdns.com":          {Name: "StackPath", Category: "CDN"},
	"stackpathcdn.com":          {Name: "StackPath", Category: "CDN"},
	"sucuri.net":                {Name: "Sucuri", Category: "Security"},
	"incapdns.net":              {Name: "Imperva (Incapsula)", Category: "Security"},
	"impervadns.net":            {Name: "Imperva", Category: "Security"},
	"heroku.com":                {Name: "Heroku", Category: "PaaS"},
	"herokuapp.com":             {Name: "Heroku", Category: "PaaS"},
	"herokudns.com":             {Name: "Heroku", Category: "PaaS"},
	"render.com":                {Name: "Render", Category: "PaaS"},
	"onrender.com":              {Name: "Render", Category: "PaaS"},
	"fly.dev":                   {Name: "Fly.io", Category: "PaaS"},
	"digitaloceanspaces.com":    {Name: "DigitalOcean Spaces", Category: "Cloud"},
	"ondigitalocean.app":        {Name: "DigitalOcean App Platform", Category: "Cloud"},
	"github.io":                 {Name: "GitHub Pages", Category: "Website"},
	"githubusercontents.com":    {Name: "GitHub", Category: "DevOps"},
	"gitlab.io":                 {Name: "GitLab Pages", Category: "Website"},
	"bitbucket.io":              {Name: "Bitbucket", Category: "DevOps"},
	"atlassian.net":             {Name: "Atlassian", Category: "Collaboration"},
	"statuspage.io":             {Name: "Statuspage (Atlassian)", Category: "Status Page"},
	"status.io":                 {Name: "Status.io", Category: "Status Page"},
	"readthedocs.io":            {Name: "Read the Docs", Category: "Documentation"},
	"gitbook.io":                {Name: "GitBook", Category: "Documentation"},
	"readme.io":                 {Name: "ReadMe", Category: "Documentation"},
	"outlook.com":               {Name: "Microsoft 365", Category: "Email"},
	"protection.outlook.com":    {Name: "Microsoft 365 (Exchange Online)", Category: "Email"},
	"mx.microsoft":              {Name: "Microsoft 365 (DANE)", Category: "Email"},
	"office365.com":             {Name: "Microsoft 365", Category: "Email"},
	"sharepoint.com":            {Name: "SharePoint Online", Category: "Collaboration"},
	"lync.com":                  {Name: "Skype for Business", Category: "Collaboration"},
	"microsoftonline.com":       {Name: "Microsoft Entra ID", Category: "Identity"},
	"msappproxy.net":            {Name: "Azure AD App Proxy", Category: "Identity"},
	"aspmx.l.google.com":        {Name: "Google Workspace", Category: "Email"},
	"googlemail.com":            {Name: "Google Workspace", Category: "Email"},
	"ghs.googlehosted.com":      {Name: "Google Sites", Category: "Website"},
	"googlehosted.com":          {Name: "Google", Category: "Cloud"},
	"stripe.com":                {Name: "Stripe", Category: "Payments"},
	"chargebee.com":             {Name: "Chargebee", Category: "Payments"},
	"recurly.com":               {Name: "Recurly", Category: "Payments"},
	"braintreegateway.com":      {Name: "Braintree (PayPal)", Category: "Payments"},
	"squareup.com":              {Name: "Square", Category: "Payments"},
	"typeform.com":              {Name: "Typeform", Category: "Forms"},
	"wufoo.com":                 {Name: "Wufoo", Category: "Forms"},
	"surveygizmo.com":           {Name: "Alchemer", Category: "Forms"},
	"unbounce.com":              {Name: "Unbounce", Category: "Landing Pages"},
	"instapage.com":             {Name: "Instapage", Category: "Landing Pages"},
	"leadpages.net":             {Name: "Leadpages", Category: "Landing Pages"},
	"canva.com":                 {Name: "Canva", Category: "Design"},
	"calendly.com":              {Name: "Calendly", Category: "Scheduling"},
	"acuityscheduling.com":      {Name: "Acuity Scheduling", Category: "Scheduling"},
	"eventbrite.com":            {Name: "Eventbrite", Category: "Events"},
	"zoom.us":                   {Name: "Zoom", Category: "Video"},
	"webex.com":                 {Name: "Webex (Cisco)", Category: "Video"},
	"auth0.com":                 {Name: "Auth0 (Okta)", Category: "Identity"},
	"okta.com":                  {Name: "Okta", Category: "Identity"},
	"onelogin.com":              {Name: "OneLogin", Category: "Identity"},
	"duosecurity.com":           {Name: "Duo (Cisco)", Category: "Identity"},
	"greenhouse.io":             {Name: "Greenhouse", Category: "Recruiting"},
	"lever.co":                  {Name: "Lever", Category: "Recruiting"},
	"workday.com":               {Name: "Workday", Category: "HR"},
	"bamboohr.com":              {Name: "BambooHR", Category: "HR"},
	"namely.com":                {Name: "Namely", Category: "HR"},
	"gusto.com":                 {Name: "Gusto", Category: "HR"},
	"slack.com":                 {Name: "Slack", Category: "Collaboration"},
	"notion.so":                 {Name: "Notion", Category: "Collaboration"},
	"monday.com":                {Name: "monday.com", Category: "Collaboration"},
	"asana.com":                 {Name: "Asana", Category: "Collaboration"},
	"pagerduty.com":             {Name: "PagerDuty", Category: "Monitoring"},
	"datadoghq.com":             {Name: "Datadog", Category: "Monitoring"},
	"datadoghq.eu":              {Name: "Datadog", Category: "Monitoring"},
	"sentry.io":                 {Name: "Sentry", Category: "Monitoring"},
	"newrelic.com":              {Name: "New Relic", Category: "Monitoring"},
	"sumologic.com":             {Name: "Sumo Logic", Category: "Monitoring"},
	"grafana.net":               {Name: "Grafana Cloud", Category: "Monitoring"},
	"docusign.com":              {Name: "DocuSign", Category: "Documents"},
	"docusign.net":              {Name: "DocuSign", Category: "Documents"},
	"hellosign.com":             {Name: "HelloSign (Dropbox)", Category: "Documents"},
	"box.com":                   {Name: "Box", Category: "Storage"},
	"dropbox.com":               {Name: "Dropbox", Category: "Storage"},
	"egnyte.com":                {Name: "Egnyte", Category: "Storage"},
	"teachable.com":             {Name: "Teachable", Category: "Learning"},
	"thinkific.com":             {Name: "Thinkific", Category: "Learning"},
	"kajabi.com":                {Name: "Kajabi", Category: "Learning"},
	"discourse.org":             {Name: "Discourse", Category: "Community"},
	"discourse.cloud":           {Name: "Discourse", Category: "Community"},
	"mattermost.com":            {Name: "Mattermost", Category: "Collaboration"},
	"tawk.to":                   {Name: "tawk.to", Category: "Live Chat"},
	"crisp.chat":                {Name: "Crisp", Category: "Live Chat"},
	"drift.com":                 {Name: "Drift", Category: "Live Chat"},
	"livechatinc.com":           {Name: "LiveChat", Category: "Live Chat"},
	"segment.com":               {Name: "Segment (Twilio)", Category: "Analytics"},
	"segment.io":                {Name: "Segment (Twilio)", Category: "Analytics"},
	"amplitude.com":             {Name: "Amplitude", Category: "Analytics"},
	"mixpanel.com":              {Name: "Mixpanel", Category: "Analytics"},
	"hotjar.com":                {Name: "Hotjar", Category: "Analytics"},
	"optimizely.com":            {Name: "Optimizely", Category: "Analytics"},
	"crazyegg.com":              {Name: "Crazy Egg", Category: "Analytics"},
	"wpenginepowered.com":       {Name: "WP Engine", Category: "Website"},
	"flywheel.io":               {Name: "Flywheel", Category: "Website"},
	"kinsta.cloud":              {Name: "Kinsta", Category: "Website"},
	"cloudwaysapps.com":         {Name: "Cloudways", Category: "Website"},
	"siteground.net":            {Name: "SiteGround", Category: "Hosting"},
	"bluehost.com":              {Name: "Bluehost", Category: "Hosting"},
	"godaddysites.com":          {Name: "GoDaddy", Category: "Hosting"},
	"secureserver.net":          {Name: "GoDaddy", Category: "Hosting"},
	"hostgator.com":             {Name: "HostGator", Category: "Hosting"},
	"dreamhost.com":             {Name: "DreamHost", Category: "Hosting"},
	"wpcomstaging.com":          {Name: "WordPress.com", Category: "Website"},
	"service-now.com":           {Name: "ServiceNow", Category: "ITSM"},
	"servicenow.com":            {Name: "ServiceNow", Category: "ITSM"},
}
